---

- name: depend - upgrade
  apt:
    upgrade=full
  when: ansible_os_family == 'Debian'

- name: depend - apt common packages
  apt:
    name={{ item }}
    state=present
    cache_valid_time=3600
    update_cache=yes
  with_items:
    - software-properties-common
    - python-pycurl
  when: ansible_os_family == 'Debian'

- name: depend - yum
  yum:
    name={{ item }}
    update_cache=yes
  with_items:
    - libselinux-python
    - MySQL-python
  when: ansible_os_family == 'RedHat'

