---

- name: users - create
  mysql_user:
    name={{ item.name }}
    password={{ item.password}}
    priv={{ item.priv }}
    state={{ item.state | default('present') }}
  with_items: mariadb_users

